INSERT INTO USER(USERNAME, PASSWORD) VALUES ('hamed', '$2a$09$pQQefyXVALOS9Fs77WnAH./M/lfrlUPt6RrdkbkAg60cQ61iaXaeG');
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('other', '$2a$09$pQQefyXVALOS9Fs77WnAH./M/lfrlUPt6RrdkbkAg60cQ61iaXaeG');
INSERT INTO AUTH_USER_GROUP(USERNAME, AUTH_GROUP) VALUES ('hamed', 'USER');
INSERT INTO AUTH_USER_GROUP(USERNAME, AUTH_GROUP) VALUES ('hamed', 'ADMIN');
INSERT INTO AUTH_USER_GROUP(USERNAME, AUTH_GROUP) VALUES ('other', 'USER');
