INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (1, 'Headphone', 2000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (2, 'Lap top', 3000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (3, 'External Hard', 6000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (4, 'Play Station', 4000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (5, 'Galaxy S9', 7000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (6, 'Sony TV', 6000);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE) VALUES (7, 'DVD Player', 7000);